package com.microservice1.microservice1.dto;

import java.io.Serializable;
//import org.naic.fs.optins.common.dto.BaseDto;

public class Users implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema.users.id
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema.users.name
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column information_schema.users.salary
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    private Integer salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema.users.id
     *
     * @return the value of information_schema.users.id
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public Users withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema.users.id
     *
     * @param id the value for information_schema.users.id
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema.users.name
     *
     * @return the value of information_schema.users.name
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public Users withName(String name) {
        this.setName(name);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema.users.name
     *
     * @param name the value for information_schema.users.name
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column information_schema.users.salary
     *
     * @return the value of information_schema.users.salary
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public Users withSalary(Integer salary) {
        this.setSalary(salary);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column information_schema.users.salary
     *
     * @param salary the value for information_schema.users.salary
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }
}