package com.microservice1.microservice1.dao;

import com.microservice1.microservice1.dto.Users;
import com.microservice1.microservice1.dto.UsersExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @SelectProvider(type=UsersSqlProvider.class, method="countByExample")
    long countByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @DeleteProvider(type=UsersSqlProvider.class, method="deleteByExample")
    int deleteByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @Delete({
        "delete from information_schema.users",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @Insert({
        "insert into information_schema.users (id, name, ",
        "salary)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{salary,jdbcType=INTEGER})"
    })
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @InsertProvider(type=UsersSqlProvider.class, method="insertSelective")
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @SelectProvider(type=UsersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    List<Users> selectByExampleWithRowbounds(UsersExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @SelectProvider(type=UsersSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    List<Users> selectByExample(UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @Select({
        "select",
        "id, name, salary",
        "from information_schema.users",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="salary", property="salary", jdbcType=JdbcType.INTEGER)
    })
    Users selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Users record, @Param("example") UsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @UpdateProvider(type=UsersSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table information_schema.users
     *
     * @mbg.generated Mon Sep 24 22:48:43 CDT 2018
     */
    @Update({
        "update information_schema.users",
        "set name = #{name,jdbcType=VARCHAR},",
          "salary = #{salary,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Users record);
}