package com.microservice1.microservice1.dao;

import com.microservice1.microservice1.dto.UserAccount;
import com.microservice1.microservice1.dto.UserAccountExample;
import java.util.List;

import org.apache.ibatis.annotations.*;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface UserAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @SelectProvider(type=UserAccountSqlProvider.class, method="countByExample")
    long countByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @DeleteProvider(type=UserAccountSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @Delete({
        "delete from public.user_account",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @Insert({
        "insert into public.user_account (userid, user_name, ",
        "address, password, ",
        "email)",
        "values (#{userid,jdbcType=INTEGER}, #{userName,jdbcType=VARCHAR}, ",
        "#{address,jdbcType=VARCHAR}, #{password,jdbcType=VARCHAR}, ",
        "#{email,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT nextval('user_account_seq')", keyProperty="userid", before=true, resultType=Integer.class)
    int insert(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @InsertProvider(type=UserAccountSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT nextval('user_account_seq')", keyProperty="userid", before=true, resultType=Integer.class)
    int insertSelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @SelectProvider(type=UserAccountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    List<UserAccount> selectByExampleWithRowbounds(UserAccountExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @SelectProvider(type=UserAccountSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    List<UserAccount> selectByExample(UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @Select({
        "select",
        "userid, user_name, address, password, email",
        "from public.user_account",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userid", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR)
    })
    UserAccount selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @UpdateProvider(type=UserAccountSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @UpdateProvider(type=UserAccountSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserAccount record, @Param("example") UserAccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @UpdateProvider(type=UserAccountSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.user_account
     *
     * @mbg.generated Wed Jan 30 19:22:28 CST 2019
     */
    @Update({
        "update public.user_account",
        "set user_name = #{userName,jdbcType=VARCHAR},",
          "address = #{address,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR}",
        "where userid = #{userid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserAccount record);
}